config/routes.rb
Rails.application.routes.draw do

  get 'health/index'
  get 'time/index'
  get 'family/index'
  get 'skills/index'
  get 'children/index'
  get 'home/index'

  get 'results/index'

  get 'static_pages/home'
  root "static_pages#show", page: 'home'

  get 'static_pages/cookies'
  get 'static_pages/accessibility'

  post 'share-plan' => 'share#index'

  namespace :admin do
    resources :home_topic_questions
    resources :skills_topic_questions
    resources :family_topic_questions
    resources :time_topic_questions
    resources :health_topic_questions
    resources :children_topic_questions
    get '/', to: redirect('/admin/pages')
  end
  # mount Fae below your admin namespec
  mount Fae::Engine => '/admin'

  get "/pages/bookadoptionevening" => "static_pages#informationevent"
  get "/pages/informationevent" => "static_pages#informationevent"

  get "/pages/:page" => "static_pages#show"
end

app/models/adoption_home_page.rb
class AdoptionHomePage < Fae::StaticPage

  @slug = 'adoption_home'

  # required to set the has_one associations, Fae::StaticPage will build these associations dynamically
  def self.fae_fields
    {
      headline: { type: Fae::TextArea },
      strapline: { type: Fae::TextArea },
      hero_image: { type: Fae::Image },
      banner: { type: Fae::TextField },
      body: { type: Fae::TextArea },
      cta_title: { type: Fae::TextField },
      cta_text: { type: Fae::TextField },
      cta_button: { type: Fae::TextField },
      about: { type: Fae::TextArea },
      cookies: { type: Fae::TextArea },
      accessibility: { type: Fae::TextArea }
    }
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/children_content_page.rb
class ChildrenContentPage < Fae::StaticPage

    @slug = 'children_content'
  
    # required to set the has_one associations, Fae::StaticPage will build these associations dynamically
    def self.fae_fields
      {
        introduction: { type: Fae::TextArea },
        kicker: {type: Fae::TextArea},
        body: { type: Fae::TextArea },
        final_result_title: {type: Fae::TextField},
      }
    end
  
  end

app/models/family_content_page.rb
class FamilyContentPage < Fae::StaticPage

  @slug = 'family_content'

  # required to set the has_one associations, Fae::StaticPage will build these associations dynamically
  def self.fae_fields
    {
      introduction: { type: Fae::TextArea },
      kicker: {type: Fae::TextArea},
      body: { type: Fae::TextArea },
      final_result_title: {type: Fae::TextField},
    }
  end

end

app/models/family_topic_question.rb
class FamilyTopicQuestion < ApplicationRecord
  include Fae::BaseModelConcern

  acts_as_list add_new_at: :top
  default_scope { order(:position) }

  def fae_display_field
    title
  end

end

app/models/health_topic_question.rb
class HealthTopicQuestion < ApplicationRecord
  include Fae::BaseModelConcern

  acts_as_list add_new_at: :top
  default_scope { order(:position) }

  def fae_display_field
    title
  end

end

app/models/home_content_page.rb
class HomeContentPage < Fae::StaticPage

  @slug = 'home_content'

  # required to set the has_one associations, Fae::StaticPage will build these associations dynamically
  def self.fae_fields
    {
      introduction: { type: Fae::TextArea },
      kicker: {type: Fae::TextArea},
      body: { type: Fae::TextArea },
      start_topic_link_text: {type: Fae::TextField},
      completed_topic_link_text: {type: Fae::TextField},
      success_text: {type: Fae::TextField},
      save_button: {type: Fae::TextField},
      final_result_title: {type: Fae::TextField},
      results: {type: Fae::TextField},
      results_link_text: {type: Fae::TextField}
    }
  end

end

app/models/home_topic_question.rb
class HomeTopicQuestion < ApplicationRecord
  include Fae::BaseModelConcern

  acts_as_list add_new_at: :top
  default_scope { order(:position) }

  def fae_display_field
    title
  end

end

app/models/lifestyle_section.rb
class LifestyleSection < ApplicationRecord
  include Fae::BaseModelConcern

  acts_as_list add_new_at: :top
  default_scope { order(:position) }

  def fae_display_field
    title
  end

end

app/models/result_content_page.rb
class ResultContentPage < Fae::StaticPage

  @slug = 'result_content'

  # required to set the has_one associations, Fae::StaticPage will build these associations dynamically
  def self.fae_fields
    {
      headline: { type: Fae::TextField }
    }
  end

end

app/models/root_settings_page.rb
class RootSettingsPage < Fae::Option
  end

app/models/skills_content_page.rb
class SkillsContentPage < Fae::StaticPage

  @slug = 'skills_content'

  # required to set the has_one associations, Fae::StaticPage will build these associations dynamically
  def self.fae_fields
    {
      introduction: { type: Fae::TextArea },
      kicker: {type: Fae::TextArea},
      body: { type: Fae::TextArea },
      final_result_title: {type: Fae::TextField},


    }
  end

end

app/models/skills_topic_question.rb
class SkillsTopicQuestion < ApplicationRecord
  include Fae::BaseModelConcern

  acts_as_list add_new_at: :top
  default_scope { order(:position) }

  def fae_display_field
    title
  end

end

app/models/time_content_page.rb
class TimeContentPage < Fae::StaticPage

  @slug = 'time_content'

  # required to set the has_one associations, Fae::StaticPage will build these associations dynamically
  def self.fae_fields
    {
      introduction: { type: Fae::TextArea },
      kicker: {type: Fae::TextArea},
      body: { type: Fae::TextArea },
      final_result_title: {type: Fae::TextField},
    }
  end

end

app/models/time_topic_question.rb
class TimeTopicQuestion < ApplicationRecord
  include Fae::BaseModelConcern

  acts_as_list add_new_at: :top
  default_scope { order(:position) }

  def fae_display_field
    title
  end

end

app/controllers/admin/skills_topic_questions_controller.rb
module Admin
  class SkillsTopicQuestionsController < Fae::BaseController

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @homeTopicContent = HomeTopicQuestion.all
    @healthContent = LifestyleContentPage.instance
    @timeContent = TimeContentPage.instance
    @familyContent = FamilyContentPage.instance
    @childrenContent = ChildrenContentPage.instance
    @skillsContent = SkillsContentPage.instance
    @homeContent = HomeContentPage.instance
    @rootSettings = RootSettingsPage.instance
    @sitehome = AdoptionHomePage.instance
  end
end

app/controllers/share_controller.rb
class ShareController < ApplicationController
  require 'kramdown'

  def index
      ShareMailer.with(recipient: params[:recipient], toDoList: params[:toDoList]).share_plan.deliver_later

      render json: { status: "sent" }
  end
end

app/controllers/time_controller.rb
class TimeController < ApplicationController
  def index
    @timeTopicContent = TimeTopicQuestion.all
    @healthContent = LifestyleContentPage.instance
    @timeContent = TimeContentPage.instance
    @familyContent = FamilyContentPage.instance
    @childrenContent = ChildrenContentPage.instance
    @skillsContent = SkillsContentPage.instance
    @homeContent = HomeContentPage.instance
    @rootSettings = RootSettingsPage.instance
    @sitehome = AdoptionHomePage.instance
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/skills_topic_questions/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_input f, :title, label: "The title of the question"
    = fae_input f, :answer_1, label: "First answer to question"
    = fae_input f, :answer_1_explanation, markdown: true, label: "Explanation of first answer"
    = fae_input f, :action_1_title, label: "First answer's action title", helper_text: "(optional)", hint: "If you add an action here it will be added to the users readiness checker results list"
    = fae_input f, :action_1_text, markdown: true, label: "First answer's action content", helper_text: "(optional)", hint: "Don't start this action with a link"
    hr
    = fae_input f, :answer_2, label: "Second answer to question"
    = fae_input f, :answer_2_explanation, markdown: true, label: "Explanation of second answer"
    = fae_input f, :action_2_title, label: "Second answer's action title", helper_text: "(optional)", hint: "If you add an action here it will be added to the users readiness checker results list"
    = fae_input f, :action_2_text, markdown: true, label: "Second answer's action content", helper_text: "(optional)", hint: "Don't start this action with a link"
    hr
    = fae_input f, :answer_3, label: "Third answer to question", helper_text: "(optional)", hint: "This answer is entirely optional, leave it blank to only have two answers for this question"
    = fae_input f, :answer_3_explanation, markdown: true, label: "Explanation of third answer", helper_text: "(optional)"
    = fae_input f, :action_3_title, label: "Third answer's action title", helper_text: "(optional)", hint: "If you add an action here it will be added to the users readiness checker results list"
    = fae_input f, :action_3_text, markdown: true, label: "Third answer's action content", helper_text: "(optional)", hint: "Don't start this action with a link"

app/views/admin/skills_topic_questions/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-row
    thead
      tr
        th.th-sortable-handle
        th Title
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td.sortable-handle: i.icon-sort
            td = link_to item.fae_display_field, edit_admin_skills_topic_question_path(item)
            td = fae_date_format item.updated_at
      - else
        tr: td colspan="4" No items found